fixed testing for autotools and cmake

diff --git a/src/tests/Makefile.in b/src/tests/Makefile.in
--- a/src/tests/Makefile.in
+++ b/src/tests/Makefile.in
@@ -1,4 +1,5 @@
 NO_COLOR=\033[0m
+SKIP_COLOR=\033[33;01m
 OK_COLOR=\033[32;01m
 ERROR_COLOR=\033[31;01m
 
@@ -98,8 +99,13 @@ test : $(TESTS)
              fi; \
              printf "\n";\
 	   else \
-	     printf " [$(ERROR_COLOR)FAILED$(NO_COLOR)]\n"; \
-             status=`expr $$status + 1`; \
+	     err=$$?; \
+	     if [[ $$err -eq 125 ]]; then \
+		printf " [$(SKIP_COLOR) SKIP $(NO_COLOR)]\n"; \
+	     else \
+		printf " [$(ERROR_COLOR)FAILED$(NO_COLOR)]\n"; \
+		status=`expr $$status + 1`; \
+	     fi; \
 	   fi; \
 	 done; \
 	 echo "=== finished ==="; \
